### PR TITLE
ES6 code refactor

### PR DESCRIPTION
**Pull request by JonatanSalas**
I started to make a big refactor in order to get all the code using the ES6 syntax. The refactor was the following: 
- Change all React.createClass() call for ES6 classes 
- Move all custom functions declared under createClass to ES6 class properties + arrow functions in order to get auto binding to the class "this". 
- Extracted all bloated code from render and moved to small and clearer functions in order to get it more easy to read and understand.  
- Fixes for minor bugs I introduce when making the refactor. 

I have tested in the browser and everything is fine. If you find something please tell me and I will make my best effort to solve it. 

When this branch it's able to merge I will start to work with two more things: 
- Add material-ui support  
- Refactor of demo app to es6 and add material-ui factory when finished.

### CODE REVIEW

**Comment by andrerpena** [comment]
That's an amazing job Jonatan.
Also, I'm looking really forward for the Material UI.
Do you want to join the project as a contributor? I can give you write access.

**Comment by JonatanSalas** [comment]
I you want to! I would like to help you grow this project!

**Comment by andrerpena** [comment]
Ok.. I'll deal with giving you rights this after noon :)

**Comment by JonatanSalas** [comment]
Great!! Thanks!

**Pull request merged**
