### PR TITLE
V1 development

### PR DESCRIPTION
**Pull request by danigomez**
This completes the issue #46 !
We should review why PhantomJS is failing to run the test (ariya/phantomjs#14096), the test are running correctly when using the Chrome browser.

### CODE REVIEW

**Comment by andrerpena** [comment]
Now this is a big refactor. Thank you @danigomez .
Of course you ran all tests and also did exploratory manual tests on the demo, right? I just wanted to confirm. If that's the case I'll just merge it and review it afterwards.

**Comment by andrerpena** [comment]
Does that mean you added 50 lines and removed 1756????

image

**Comment by JonatanSalas** [comment]
@andrerpena I have removed the demo from v1-development too. That's why this is a big refactor. It was my fault, I pushed to v1-development and then I forget that I should delete the demo from master. Bad mine :confused:

**Comment by danigomez** [comment]
@andrerpena Yes!, all the karma test passed using Chrome, but are failing with PhantomJS for some reason....  i also tested in the demo an all is still working!

**Comment by JonatanSalas** [comment]
@andrerpena I wil merge it now! @danigomez tested locally that this is working and still works really good. Then you can review it! :smile:

**Comment by andrerpena** [comment]
Ok thank you both

**Pull request merged**
