### PR TITLE
V1 development

### PR DESCRIPTION
**Pull request by JonatanSalas**
Well, I know that this can't be merged automatically because of the changes that have been made to the master branch. 

I will create this PR to let you know some part of the changes I have made, and I will keep work on this till we can merge automatically without any trouble. 

@andrerpena would you like to explain me which are the files that you have changed, so i can look on them and update this branch.

### CODE REVIEW

**Comment by JonatanSalas** [comment]
@andrerpena everything now it's working fine. Could you please take a look if it works for you? I have done first a manual merge and then an automatic merge. I have tested local and everything is up and running :) 

This PR introduce the following changes: 
- We add redux-autoform-utils as a depedency in package.json 
- We delete all code related to UI since redux-autoform-bootstrap-ui has been released
- The demo is adapted to work with redux-autoform-bootstrap-ui and everything works as expected
- It has all the changes that you have added working properly. 
- I have added UIManager class to manage the black magic of factory injection when you supply a uiType, this is not tested yet and may need a bit more of work, so for now we keep on passing the componentFactory to autoForm

Well, that's all! We are rocking! :smile:

**Comment by andrerpena** [comment]
Jonatas, I'll only have time to work on this Saturday morning. The only major changes I've done lately is the simpler schema syntax. If you are confident these are working, and you're to excited to wait, you can merge it yourself.

As a side note, I'd like to discuss more about what should be in the separate lib, because can make it harder to go forward. The only things I'm 100% positive should be in a separate library are things that should be shared across different UI. But anyway, if you want to merge it anyways, I can look into what I don't agree on separating this weekend and let you know.

**Comment by JonatanSalas** [comment]
@andrerpena Okey, I will merge it, and then when you have some time take a look and modify what you don't like! There's no trouble! :smile:

**Comment by andrerpena** [comment]
@JonatanSalas it seems to be working. Thanks for the great work. Again.. My only concern is the actuall necessity / what should really be in this external library, but I'm really appreciating what you've being doing.

**Comment by JonatanSalas** [comment]
@andrerpena okey! When you have some time let's discuss about this here #38

**Pull request merged**
